# Generated by Django 3.1.4 on 2021-01-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_loggedinuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoggedInUser',
        ),
    ]
